

name: Blackduck_CI_POC

on: 
  workflow_dispatch:
jobs:
  Blackduck_Scan_trigger:

      runs-on: 
      steps:
      - name: checkout
        uses: actions/checkout@2v2
        
  Blackduck_Scan:
        uses: ./.github/workflows/reusable-blackduck-scan-workflow.yml
        with:
          SourcePath: 'Modules'
          ProjectVersion: 'test123'
          ExcludeDirectories: './SecopsIntakePortal/CustomClaimHelpers,./SecopsIntakePortal/nginx'
          ProjectTag: 'vci'
          NoticeReportPath: './Security/BlackDuckReports/'
          RiskReportPath: './Security/BlackDuckReports/'
        secrets:
          NEW_GITHUB_TOKEN: ${{ secrets.NEW_GITHUB_TOKEN }}
          BLACKDUCK_API_TOKEN: ${{ secrets.BLACKDUCK_API_TOKEN }}
          BLACKDUCK_URL: ${{ secrets.BLACKDUCK_URL }}
        
 
