name: Reusable Blackduck Scan Workflow

on:
  workflow_call:
    inputs:
      SourcePath:
        type: string
        required: true
      ProjectVersion:
        type: string
        required: true
      ExcludeDirectories:
        type: string
        required: true
      ProjectTag:
        type: string
        required: true
      NoticeReportPath:
        type: string
        required: true
      RiskReportPath:
        type: string
        required: true
    secrets:
      NEW_GITHUB_TOKEN:
        required: true
      BLACKDUCK_API_TOKEN:
        required: true
      BLACKDUCK_URL:
        required: true
jobs:
  blackduck_scan:
   runs-on: [ ubuntu-latest ]
   steps:
    - uses: actions/checkout@v4
    - name: Run Black Duck Scan
      run: |
        blackduck_properties=(
          "--blackduck.url="
          "--detect.policy.check.fail.on.severities=ALL"
          "--blackduck.api.token="
          "--detect.source.path=Modules"
          "--detect.project.name="
          "--detect.project.version.name=test123"
          "--detect.project.codelocation.unmap=TRUE"
          "--detect.project.tags=vci"
          "--detect.detector.search.depth="
          "--detect.notices.report=TRUE"
          "--detect.notices.report.path=./Security/BlackDuckReports/"
          "--detect.risk.report.pdf=TRUE"
          "--detect.risk.report.pdf.path=./Security/BlackDuckReports/"
          "--detect.blackduck.signature.scanner.copyright.search=TRUE"
          "--detect.blackduck.signature.scanner.license.search=TRUE"
          "--detect.blackduck.signature.scanner.upload.source.mode=TRUE"
          "--detect.excluded.directories=./SecopsIntakePortal/CustomClaimHelpers,./SecopsIntakePortal/nginx"
        )
        echo "Running Black Duck Scan on Linux"
        echo "blackduck_properties = ${blackduck_properties[*]}"
        bash <(curl -s -L https://detect.synopsys.com/detect9.sh) "${blackduck_properties[@]}"
